Update build-armbian - test.yml

diff --git a/.github/workflows/build-armbian - test.yml b/.github/workflows/build-armbian - test.yml
--- a/.github/workflows/build-armbian - test.yml
+++ b/.github/workflows/build-armbian - test.yml
@@ -111,10 +111,47 @@ jobs:
         run: |  
           # 提取版本号
           latest_image=$(ls ${{ github.workspace }}/build/output/images/Armbian-unofficial_*.img.xz | grep -oE 'Armbian-unofficial_[0-9.]+_.*' | sort -V | tail -n 1)    
-          version=$(echo "$latest_image" | cut -d'_' -f2)  
-  
+          version=$(echo "$latest_image" | cut -d'_' -f2)   
+
+          # 提取板子型号
+          board_model=$(echo "$latest_image" | cut -d'_' -f3)
+      
+          # 提取内核版本号    
+          kernel_version=$(echo "$latest_image" | awk -F'_' '{for(i=1;i<=NF;i++) if($i ~ /^[0-9]+\.[0-9]+\.[0-9]+$/) version=$i; if(i==NF) print version; exit}')  
+
+          # 验证kernel_version是否已正确设置（可选）  
+          if [ -z "$kernel_version" ]; then  
+            echo "Kernel version not found in filename: $latest_image"  
+            exit 1  
+          fi 
+      
           # 将版本号设置为环境变量  
           echo "VERSION=$version" >> $GITHUB_ENV
+          echo "BOARD_MODEL=$board_model" >> $GITHUB_ENV 
+          echo "KERNEL_VERSION=$kernel_version" >> $GITHUB_ENV
+         
+      - name: Prepare Kernel Packages  
+        run: |  
+          cd "${GITHUB_WORKSPACE}/build/output/packages-hashed/"  
+      
+          # 使用find命令查找匹配的文件  
+          # 我们只关心以 'kernel-rockchip64-' 开头并以 '_arm64.tar' 结尾的文件  
+          for file in kernel-rockchip64-*_arm64.tar; do  
+          # 检查文件是否确实存在  
+            if [ -f "$file" ]; then    
+          
+                # 重命名文件  
+                mv "$file" "kernel_rockchip64_${KERNEL_VERSION}_${{ env.BOARD_MODEL }}.tar"  
+          
+                # 移动重命名的文件到目标位置  
+                mv "kernel_rockchip64_${KERNEL_VERSION}_${{ env.BOARD_MODEL }}.tar" "${GITHUB_WORKSPACE}/"  
+          
+                # 可选：打印一条消息以确认文件已被移动  
+                echo "Moved $file to ${GITHUB_WORKSPACE}/"  
+            else  
+                echo "File $file not found."  
+            fi  
+          done 
         
       - name: Upload image to Release  
         if: success() 
